package main.java.conexao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class DBConn {
    private final Connection connection;

    public DBConn(Connection connection) {
        this.connection = connection;
    }

    public PreparedStatement statement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    public PreparedStatement statement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public Connection getConnection() {
        return connection;
    }
}